name: Build Project

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Check Gradle file existence
        id: gradle_build_check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "build.gradle"

      - name: Check Maven file existence
        id: maven_pom_check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "pom.xml"

      - name: Build with Gradle
        if: steps.gradle_build_check_files.outputs.files_exists == 'true'
        # Only runs if all the files exists
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Build with Maven
        if: steps.maven_pom_check_files.outputs.files_exists == 'true'
        # Only runs if all the files exists
        run: mvn -B package --file pom.xml
